services:
  frontend:
    image: voyagr-frontend:latest
    container_name: voyagr-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - voyagr-network
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt/live/voyagr.me:/etc/nginx/ssl/live/voyagr.me:ro
      - /etc/letsencrypt/archive/voyagr.me:/etc/nginx/ssl/archive/voyagr.me:ro

  backend:
    image: voyagr-backend:latest
    container_name: voyagr-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - voyagr-network
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      NODE_ENV: ${NODE_ENV}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      BACKEND_SESSION_SECRET: ${BACKEND_SESSION_SECRET}
    depends_on:
      - redis      
      - postgres

  redis:
    image: redis:latest
    container_name: manageme-redis
    ports:
      - "6379:6379"
    networks:
      - voyagr-network

  postgres:
    image: postgres:16
    container_name: voyagr-db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voyagr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      bash -c '
        echo "Database Environment Variables:"
        echo "DB_NAME: $${DB_NAME}"
        echo "DB_USER: $${DB_USER}"
        echo "DB_PASSWORD: $${DB_PASSWORD}"
        docker-entrypoint.sh postgres'

  pgadmin:
    image: dpage/pgadmin4
    container_name: voyagr-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - voyagr-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  voyagr-network:
    external: true