services:
  frontend:
    image: voyagr-frontend:latest
    container_name: voyagr-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - voyagr-network
    depends_on:
      - backend
  backend:
    image: voyagr-backend:latest
    container_name: voyagr-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - voyagr-network
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: voyagr_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      SESSION_SECRET: ${SESSION_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy

networks:
  voyagr-network:
    external: true