services:
  frontend:
    image: voyagr-frontend:latest
    container_name: voyagr-frontend
    restart: unless-stopped
    # Ports removed - proxy handles external access
    networks:
      - voyagr-network
      - proxy-network
    depends_on:
      - backend
    # SSL volumes removed - proxy handles SSL termination

  backend:
    image: voyagr-backend:latest
    container_name: voyagr-backend
    restart: unless-stopped
    # Port mapping removed - only accessible via proxy network
    networks:
      - voyagr-network
      - proxy-network
    environment:
      POSTGRES_HOST: postgres
      NODE_ENV: PRODUCTION
      FRONTEND_URL: https://voyagr.me/
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      BACKEND_SESSION_SECRET: ${BACKEND_SESSION_SECRET}
      REDIS_URL: redis://voyagr-redis:6379
    depends_on:
      - redis      
      - postgres

  redis:
    image: redis:latest
    container_name: voyagr-redis
    # Port mapping removed - internal access only
    networks:
      - voyagr-network
      - proxy-network

  postgres:
    image: postgres:16
    container_name: voyagr-db
    environment:
      POSTGRES_DB: voyagr
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # Port mapping removed - internal access only
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voyagr-network
      - proxy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  voyagr-network:
    external: true
  proxy-network:
    external: true