services:
  postgres:
    image: postgres:16
    container_name: voyagr-db
    environment:
      POSTGRES_DB: voyagr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: voyagr-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: 