name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy to LXC
    runs-on: self-hosted
    environment: prod
    
    env:
      # GitHub Runner
      DOCKER_HOST: tcp://10.0.0.35:2375
      DOCKER_CONTEXT_NAME: voyagr-ctx
      DOCKER_COMPOSE_FILE: docker-compose.prod.yml
      FRONTEND_IMAGE: voyagr-frontend:latest
      BACKEND_IMAGE: voyagr-backend:latest

      # Shared by Frontend and Backend
      AUTH0_DOMAIN: dev-m0q23jbgtbwidn00.us.auth0.com

      # Backend Secrets - From GitHub Secrets
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      BACKEND_SESSION_SECRET: ${{ secrets.BACKEND_SESSION_SECRET }}
      
      # FRONTEND
      # frontend env variables are set at build time, see Build Frontend step
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend image
        run: |
          docker build \
            -f Dockerfile.frontend \
            -t ${{ env.FRONTEND_IMAGE }} \
            --build-arg VITE_AUTH0_DOMAIN=dev-m0q23jbgtbwidn00.us.auth0.com \
            --build-arg VITE_AUTH0_CLIENT_ID=jJhP7FGnwad8ibaRpnhOjdHqJ69eilVn \
            .

      - name: Build Backend image
        run: |
          docker build \
            -f Dockerfile.backend \
            -t ${{ env.BACKEND_IMAGE }} \
            .

      - name: Set up Docker context
        run: |
          docker context \
            create ${{ env.DOCKER_CONTEXT_NAME }} \
            --docker host=${{ env.DOCKER_HOST }}

      - name: Save and load images to remote Docker
        run: |
          # Save images
          docker save ${{ env.FRONTEND_IMAGE }} > frontend.tar
          docker save ${{ env.BACKEND_IMAGE }} > backend.tar
          
          # Load images on remote host
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} load < frontend.tar
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} load < backend.tar
          
          # Cleanup
          rm frontend.tar backend.tar

      - name: Create volume if not exists
        run: |
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} volume create voyagr-data || true

      - name: Stop and remove existing containers
        env:
          COMPOSE_PROJECT_NAME: voyagr
        run: |
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} compose --file ${{ env.DOCKER_COMPOSE_FILE }} \
            stop frontend backend || true
          
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} compose --file ${{ env.DOCKER_COMPOSE_FILE }} \
            rm -f frontend backend || true
          
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} compose --file ${{ env.DOCKER_COMPOSE_FILE }} \
            up -d --remove-orphans

      - name: Cleanup
        if: always()
        run: |
          docker context rm ${{ env.DOCKER_CONTEXT_NAME }} --force || true


