name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy to LXC
    runs-on: self-hosted
    environment: prod
    
    env:
      DOCKER_HOST: tcp://10.0.0.35:2375
      DOCKER_CONTEXT_NAME: voyagr-ctx
      DOCKER_COMPOSE_FILE: docker-compose.yml
      FRONTEND_IMAGE: voyagr-frontend:latest
      BACKEND_IMAGE: voyagr-backend:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat << EOF > .env
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          FRONTEND_URL=${{ secrets.FRONTEND_URL }}
          PGADMIN_EMAIL=${{ secrets.PGADMIN_EMAIL }}
          PGADMIN_PASSWORD=${{ secrets.PGADMIN_PASSWORD }}
          AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}
          EOF

      - name: Build Frontend image
        run: |
          docker build \
            -f Dockerfile.frontend \
            -t ${{ env.FRONTEND_IMAGE }} \
            .

      - name: Build Backend image
        run: |
          docker build \
            -f Dockerfile.backend \
            -t ${{ env.BACKEND_IMAGE }} \
            .

      - name: Set up Docker context
        run: |
          docker context \
            create ${{ env.DOCKER_CONTEXT_NAME }} \
            --docker host=${{ env.DOCKER_HOST }}

      - name: Save and load images to remote Docker
        run: |
          # Save images
          docker save ${{ env.FRONTEND_IMAGE }} > frontend.tar
          docker save ${{ env.BACKEND_IMAGE }} > backend.tar
          
          # Load images on remote host
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} load < frontend.tar
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} load < backend.tar
          
          # Cleanup
          rm frontend.tar backend.tar

      - name: Create volume if not exists
        run: |
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} volume create voyagr-db-data || true

      - name: Stop and remove existing containers
        run: |
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} compose --file ${{ env.DOCKER_COMPOSE_FILE }} \
            --env-file .env \
            stop frontend backend || true
          
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} compose --file ${{ env.DOCKER_COMPOSE_FILE }} \
            --env-file .env \
            rm -f frontend backend || true
          
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} compose --file ${{ env.DOCKER_COMPOSE_FILE }} \
            --env-file .env \
            up -d --remove-orphans

      - name: Debug Environment Variables
        run: |
          echo "Checking .env file contents (with secrets redacted):"
          echo "DB_USER exists: $(if [ -n "${{ secrets.DB_USER }}" ]; then echo "yes"; else echo "no"; fi)"
          echo "DB_PASSWORD exists: $(if [ -n "${{ secrets.DB_PASSWORD }}" ]; then echo "yes"; else echo "no"; fi)"
          echo "DB_NAME exists: $(if [ -n "${{ secrets.DB_NAME }}" ]; then echo "yes"; else echo "no"; fi)"
          echo "DB_HOST exists: $(if [ -n "${{ secrets.DB_HOST }}" ]; then echo "yes"; else echo "no"; fi)"
          echo "DB_PORT exists: $(if [ -n "${{ secrets.DB_PORT }}" ]; then echo "yes"; else echo "no"; fi)"
          
          echo "Checking Docker container environment:"
          docker --context ${{ env.DOCKER_CONTEXT_NAME }} compose --file ${{ env.DOCKER_COMPOSE_FILE }} \
            --env-file .env \
            exec -T postgres printenv | grep POSTGRES

      - name: Cleanup
        if: always()
        run: |
          docker context rm ${{ env.DOCKER_CONTEXT_NAME }} --force || true
          rm .env || true


