name: Build and Release Electron App

on:
  push:
    branches:
      - main

permissions:
  contents: write  # This is required for creating releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # We'll specify the cache path specifically for electron directory
          cache: 'npm'
          cache-dependency-path: frontend/electron/package-lock.json
          
      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
          
      # Install electron dependencies  
      - name: Install electron dependencies
        run: |
          cd frontend/electron
          npm ci
          
      # Build frontend (assuming this needs to be done before electron build)
      - name: Build frontend
        run: |
          cd frontend
          npm run build
          
      # Run electron make
      - name: Create electron release
        run: |
          cd frontend/electron
          npm run electron:make
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            frontend/electron/dist/*.dmg
            frontend/electron/dist/*.exe
            frontend/electron/dist/*.AppImage
            frontend/electron/dist/*.snap
            frontend/electron/dist/*.deb
            frontend/electron/dist/*.rpm
            
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}